### ISSUE TITLE
awtk-web编译js项目报错

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-jerryscript#10]
环境：Win10
步骤：
1.获取 awtk 并编译
```
git clone https://github.com/zlgopen/awtk.git
cd awtk; scons; cd 
```
通过。

2.获取 awtk-jerryscript 并编译
```
git clone https://github.com/zlgopen/awtk-jerryscript.git
cd awtk-jerryscript
git clone https://github.com/jerryscript-project/jerryscript.git 3rd/jerryscript/jerryscript
cd 3rd/jerryscript/jerryscript
git reset --hard 3737a28eafd580a2bee2794e4f5edd0c0471a0c6
```
通过。

3.运行
```
cd d:/awtk-jerryscript
.\bin\awtkRun.exe  .\res\assets\default\raw\scripts\demoui.js
```
运行demo示例正常

4.部署到浏览器
修改D:\awtk-jerryscript\design\default\scripts\demoui_web.json

{
  "name":"demouijs",
  "version":"1.0",
  "app_type":"js",
  "assets" : "../../../../awtk/design",  //原assets路径为："../../../awtk/design"
  "sources":["demoui.js"]
}

编译:
```
cd ../awtk-web
python build.py D:\awtk-jerryscript\design\default\scripts\demoui_web.json all
```

输出：
```
...
"D:\\emsdk\\upstream\\bin\\clang.exe" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb "-fdebug-compilation-dir=D:\\awtk-web" -v "-fcoverage-compilation-dir=D:\\awtk-web" -resource-dir "D:\\emsdk\\upstream\\lib\\clang\\19" -isystem "D:\\emsdk\\upstream\\emscripten\\cache\\sysroot\\include\\SDL2" -D EMSCRIPTEN -D SAFE_HEAP=1 -D ASSERTIONS=1 -D STACK_OVERFLOW_CHECK=1 -D AWTK_WEB_JS -D WITH_DATA_READER_WRITER -D HAS_STD_MALLOC -D NDEBUG -D AWTK_WEB -I src/c -D WITH_WINDOW_ANIMATORS -D WITH_NANOVG_GPU -I "D:\\awtk-web\\webroot\\demouijs\\res" -I "D:\\awtk/3rd" -I "D:\\awtk" -I "D:\\awtk\\src" -I "D:\\awtk\\src/ext_widgets" -isysroot "D:\\emsdk\\upstream\\emscripten\\cache\\sysroot" -internal-isystem "D:\\emsdk\\upstream\\lib\\clang\\19\\include" -internal-isystem "D:\\emsdk\\upstream\\emscripten\\cache\\sysroot/include/wasm32-emscripten" -internal-isystem "D:\\emsdk\\upstream\\emscripten\\cache\\sysroot/include" -Werror=implicit-function-declaration -ferror-limit 19 -fmessage-length=120 -fvisibility=default -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fignore-exceptions -fcolor-diagnostics "-iwithsysroot/include\\compat" -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o "C:\\Users\\nihaoa\\AppData\\Local\\Temp\\emscripten_temp_peq6rwbh\\main_302.o" -x c "D:\\awtk-web\\src\\c\\main.c"
clang -cc1 version 19.0.0git based upon LLVM 19.0.0git default target x86_64-pc-windows-msvc
ignoring nonexistent directory "D:\emsdk\upstream\emscripten\cache\sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 src/c
 D:\awtk-web\webroot\demouijs\res
 D:\awtk/3rd
 D:\awtk
 D:\awtk\src
 D:\awtk\src/ext_widgets
 D:\emsdk\upstream\emscripten\cache\sysroot\include\SDL2
 D:\emsdk\upstream\emscripten\cache\sysroot/include\compat
 D:\emsdk\upstream\lib\clang\19\include
 D:\emsdk\upstream\emscripten\cache\sysroot/include
End of search list.
D:\awtk-web\src\c\main.c:11:10: fatal error: 'assets_web.inc' file not found
   11 | #include "assets_web.inc"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
emcc: error: 'D:/emsdk/upstream/bin\clang.exe -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=D:\emsdk\upstream\emscripten\cache\sysroot -DEMSCRIPTEN -Werror=implicit-function-declaration -isystem D:\emsdk\upstream\emscripten\cache\sysroot\include\SDL2 -Xclang -iwithsysroot/include\compat -v -g3 -g -DSAFE_HEAP=1 -DASSERTIONS=1 -DSTACK_OVERFLOW_CHECK=1 -DAWTK_WEB_JS -DWITH_DATA_READER_WRITER -DHAS_STD_MALLOC -DNDEBUG -DAWTK_WEB -Isrc/c -DWITH_WINDOW_ANIMATORS -DWITH_NANOVG_GPU -ID:\awtk-web\webroot\demouijs\res -ID:\awtk/3rd -ID:\awtk -ID:\awtk\src -ID:\awtk\src/ext_widgets D:\awtk-web\src\c\main.c -c -o C:\Users\nihaoa\AppData\Local\Temp\emscripten_temp_peq6rwbh\main_302.o' failed (returned 1)
D:\awtk-web\webroot\demouijs\js\app.js
api/awtk_api_browser_prefix.js
api/awtk_api.js
D:\awtk-jerryscript\design\default\scripts\demoui.js
['api/awtk_api_browser_prefix.js', 'api/awtk_api.js', 'D:\\awtk-jerryscript\\design\\default\\scripts\\demoui.js'] D:\awtk-web\webroot\demouijs\js\app.js
D:\awtk-web\webroot\demouijs\js\awtk_web.js
D:\awtk-web\webroot\demouijs\assets_web.js
src/js/browser.js
gen/app_config.js
src/js/webgl2d.js
src/js/image_cache.js
src/js/assets_manager.js
src/js/image_loader.js
src/js/input_method_web.js
src/js/utils.js
src/js/edit_element.js
src/js/vgcanvas_web.js
src/js/awtk_wrap.js
src/js/key_event.js
src/js/events_source.js
src/js/main_loop_web.js
```

**Comment by Tracker647** [comment]
另外，请问后面有支持awtk designer基于js开发图形界面的计划吗，我们这边需求是看看能不能基于js做设备的web界面，因为领导觉得c效率很慢，现在来看js是只能通过代码裸编程没有界面预览，如果后期能安排上的话，那就太好了，感激不尽。

还有js文件要怎么调试呢？

**Comment by xianjimli** [comment]
awtk-web 用js开发，除了我写过一个demo外，基本上没有人用过，可能有很多坑，别在项目中使用！做web应用还是建议使用vue.js/react.js等专业框架。

**Comment by Tracker647** [comment]
好的。
目前来看，只能通过在awtk designer上写c编程然后通过awtk-web来部署到浏览器。
不知道部署到浏览器的gui app只能作为展示呢，还是能自己加上协议栈做网络通信，文件/数据库存储实现一个web app呢？

**Comment by xianjimli** [comment]
>  #include <emscripten.h>
AWTK 只能做界面，可以在web端提供Rest API，在C里用emscripten的接口去调用XMLHttpRequest发送请求，浏览器里只能用HTTP/websocket协议，不能用socket通讯。

**Comment by Tracker647** [comment]
那问下这个asset_web.inc缺失的问题算是没有办法解决了吗，这个的生成逻辑是什么，个人有没有办法自行配置解决呢
**D:\Devtools\awtk-web\src\c\main.c:11:10: fatal error: 'assets_web.inc' file not found
   11 | #include "assets_web.inc"**

**Comment by xianjimli** [comment]
已解决。你更新一下 awtk和awtk-web再试试，谢谢。

**Comment by Tracker647** [comment]
已跑通，感谢。
大佬周末还在加班加点, 辛苦了。

**Comment by Tracker647** [comment]
顺便问下，这个有办法断点调试吗？

**Comment by xianjimli** [comment]
浏览器中按F12可以调试JS，百度一下。

**Comment by Tracker647** [comment]
好的。还有三个问题：
1.桌面端上调试可能应用会更宽泛一些，demo本身就是在桌面端上运行的，问下大佬开发js界面文件的时候桌面端是用什么调试呢？
2.大佬的调试方法需要依赖具体的开发环境和IDE吗？（本人是用vscode，发现一个问题是js左键没法跳转到对应的文件依赖上去，比如demoui.js的一些api实现ctrl+左键没法调到awtk.js上，不知道咋解决）
3.我们需求是做的海图编辑，需要用到3D绘画组件，不知道awtk上有对应组件吗？

**Comment by xianjimli** [comment]
1. 我只知道在浏览器的调试方法。
2. 没用过。
3. 如果你的应用是在浏览器上跑，直接用HTML开发，有很多3D库可以用，不要用AWTK。如果在桌面上跑，AWTK集成了OGRE，你可以看看awtk-ogre项目。

**Comment by Tracker647** [comment]
又出现同样的问题，awtk, awtk-web, awtk-jerryscript的git版本都是最新的，不过换了下路径：

```
PS D:\Devtools> ls


    目录: D:\Devtools


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2024/5/27     18:15                awtk
d-----         2024/5/25     11:32                awtk-binding
d-----         2024/5/28      9:22                awtk-jerryscript
d-----         2024/5/25     18:35                awtk-quickjs
d-----         2024/5/25     17:13                awtk-restful-httpd
d-----         2024/5/27      9:09                awtk-web
d-----         2024/5/28      9:08                emsdk
d-----         2024/5/24     14:07                mingw64
d-----         2024/4/30     17:08                nodejs
d-----         2024/5/24     11:29                Python
```



步骤：

```
cd d:/devtools
cd ./emsdk
./emsdk_env
cd ../awtk-web
python build.py ..\awtk-jerryscript\design\default\scripts\demoui_web.json all
```



输出：

```
PS D:\devtools\awtk-web> python build.py ..\awtk-jerryscript\design\default\scripts\demoui_web.json all
gen exist.
gen/c exist.
gen/ts exist.
D:\devtools\awtk-jerryscript\awtk\design=>D:\devtools\awtk-web\webroot\demouijs\design
D:\devtools\awtk-jerryscript\awtk\design=>D:\devtools\awtk-web\webroot\demouijs\design
scripts=>D:\devtools\awtk-web\webroot\demouijs\scripts
scripts=>D:\devtools\awtk-web\webroot\demouijs\scripts
AWTK_ROOT: D:\Devtools\awtk
AWTK_SCRIPTS_ROOT: D:\Devtools\awtk\scripts
Expecting value: line 1 column 1 (char 0)
not found or not parsered D:\Devtools\awtk-web\webroot\demouijs\project.json, so use default config
Traceback (most recent call last):
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 41, in <module>
    update_res(ARGUMENTS, is_new_usage)
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 31, in update_res
    updater.run(locator.getAwtkRoot())
  File "D:\Devtools\awtk\scripts\update_res_app.py", line 251, in run
    theme["lcd_orientation"] = LCD_ORIENTATION
    ~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object does not support item assignment
AWTK_ROOT: D:\Devtools\awtk
AWTK_SCRIPTS_ROOT: D:\Devtools\awtk\scripts
Expecting value: line 1 column 1 (char 0)
not found or not parsered D:\Devtools\awtk-web\webroot\demouijs\project.json, so use default config
Traceback (most recent call last):
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 41, in <module>
    update_res(ARGUMENTS, is_new_usage)
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 31, in update_res
    updater.run(locator.getAwtkRoot())
  File "D:\Devtools\awtk\scripts\update_res_app.py", line 251, in run
    theme["lcd_orientation"] = LCD_ORIENTATION
    ~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object does not support item assignment
AWTK_ROOT: D:\Devtools\awtk
AWTK_SCRIPTS_ROOT: D:\Devtools\awtk\scripts
Expecting value: line 1 column 1 (char 0)
not found or not parsered D:\Devtools\awtk-web\webroot\demouijs\project.json, so use default config
Traceback (most recent call last):
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 41, in <module>
    update_res(ARGUMENTS, is_new_usage)
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 31, in update_res
    updater.run(locator.getAwtkRoot())
  File "D:\Devtools\awtk\scripts\update_res_app.py", line 251, in run
    theme["lcd_orientation"] = LCD_ORIENTATION
    ~~~~~^^^^^^^^^^^^^^^^^^^
  ...
End of search list.
D:\devtools\awtk-web\src\c\main.c:11:10: fatal error: 'assets.inc' file not found
   11 | #include "assets.inc"
      |          ^~~~~~~~~~~~
1 error generated.
emcc: error: 'D:/Devtools/emsdk/upstream/bin\clang.exe -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=D:\Devtools\emsdk\upstream\emscripten\cache\sysroot -DEMSCRIPTEN -Werror=implicit-function-declaration -isystem D:\Devtools\emsdk\upstream\emscripten\cache\sysroot\include\SDL2 -Xclang -iwithsysroot/include\compat -v -g3 -g -DSAFE_HEAP=1 -DASSERTIONS=1 -DSTACK_OVERFLOW_CHECK=1 -DAWTK_WEB_JS -DWITH_DATA_READER_WRITER -DHAS_STD_MALLOC -DNDEBUG -DAWTK_WEB -Isrc/c -DWITH_WINDOW_ANIMATORS -DWITH_NANOVG_GPU -ID:\devtools\awtk-web\webroot\demouijs\res -ID:\devtools\awtk/3rd -ID:\devtools\awtk -ID:\devtools\awtk\src -ID:\devtools\awtk\src/ext_widgets D:\devtools\awtk-web\src\c\main.c -c -o C:\Users\nihaoa\AppData\Local\Temp\emscripten_temp_sx0lv9pt\main_303.o' failed (returned 1)
D:\devtools\awtk-web\webroot\demouijs\js\app.js
api/awtk_api_browser_prefix.js
api/awtk_api.js
D:\devtools\awtk-jerryscript\design\default\scripts\demoui.js
['api/awtk_api_browser_prefix.js', 'api/awtk_api.js', 'D:\\devtools\\awtk-jerryscript\\design\\default\\scripts\\demoui.js'] D:\devtools\awtk-web\webroot\demouijs\js\app.js
D:\devtools\awtk-web\webroot\demouijs\js\awtk_web.js
D:\devtools\awtk-web\webroot\demouijs\assets_web.js
Traceback (most recent call last):
  File "D:\devtools\awtk-web\build.py", line 368, in <module>
    run(app_root, config, action)
  File "D:\devtools\awtk-web\build.py", line 339, in run
    build_awtk_web_js(config)
  File "D:\devtools\awtk-web\build.py", line 154, in build_awtk_web_js
    merge_files(awtk_web_js_files, outfile)
  File "D:\devtools\awtk-web\build.py", line 48, in merge_files
    with open(fname, encoding='utf-8-sig') as infile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\devtools\\awtk-web\\webroot\\demouijs\\assets_web.js'
```







这次demoui_web.json没改，assets用默认路径， 直接把awtk文件夹复制到了awtk-jerryscript下方。

```
{
  "name":"demouijs",
  "version":"1.0",
  "app_type":"js",
  "assets" : "../../../awtk/design",
  "sources":["demoui.js"]
}
```



但是`python build.py ..\awtk-jerryscript\build_web.json all`就没这个问题

```
PS D:\devtools\awtk-web> python build.py ..\awtk-jerryscript\build_web.json all
D:\devtools\awtk-web\webroot\demouijs\js exist.
gen exist.
gen/c exist.
gen/ts exist.
D:\devtools\awtk-jerryscript\design=>D:\devtools\awtk-web\webroot\demouijs\design
D:\devtools\awtk-jerryscript\design=>D:\devtools\awtk-web\webroot\demouijs\design
scripts=>D:\devtools\awtk-web\webroot\demouijs\scripts
scripts=>D:\devtools\awtk-web\webroot\demouijs\scripts
AWTK_ROOT: D:\Devtools\awtk
AWTK_SCRIPTS_ROOT: D:\Devtools\awtk\scripts
=========================================================
clean res: D:\Devtools\awtk-web\webroot\demouijs\res
dir D:\Devtools\awtk-web\webroot\demouijs\res not exist
=========================================================
=========================================================
"D:\Devtools\awtk\bin\strgen.exe" "D:\Devtools\awtk-web\webroot\demouijs\design\default\strings" "D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\raw\strings" bin
write D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\raw\strings/en_US.bin
write D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\raw\strings/zh_CN.bin

"D:\Devtools\awtk\bin\strgen.exe" "D:\Devtools\awtk-web\webroot\demouijs\design\default\strings" "D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\inc\strings" data default
filename=D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\inc\strings/en_US.data prefix=strings name=en_US size=9194
write D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\inc\strings/en_US.data
filename=D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\inc\strings/zh_CN.data prefix=strings name=zh_CN size=9287
write D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\inc\strings/zh_CN.data

copy file: D:\Devtools\awtk-web\webroot\demouijs\design\default\fonts\ap.ttf ==> D:\Devtools\awtk-web\webroot\demouijs\res\assets\default\raw\fonts\ap.ttf
。。。。
```



我看前面的python会报错，以为是asset路径问题，我把demoui.json的assets路径改成`../../../design`,

还是会报错，但明明和`build_web.json`输出的asset路径一样，都是`D:\devtools\awtk-jerryscript\design`, 不知道为什么。

```
PS D:\devtools\awtk-web> python build.py ..\awtk-jerryscript\design\default\scripts\demoui_web.json all
D:\devtools\awtk-web\webroot\demouijs\js exist.
gen exist.
gen/c exist.
gen/ts exist.
D:\devtools\awtk-jerryscript\design=>D:\devtools\awtk-web\webroot\demouijs\design
D:\devtools\awtk-jerryscript\design=>D:\devtools\awtk-web\webroot\demouijs\design
scripts=>D:\devtools\awtk-web\webroot\demouijs\scripts
scripts=>D:\devtools\awtk-web\webroot\demouijs\scripts
AWTK_ROOT: D:\Devtools\awtk
AWTK_SCRIPTS_ROOT: D:\Devtools\awtk\scripts
Expecting value: line 1 column 1 (char 0)
not found or not parsered D:\Devtools\awtk-web\webroot\demouijs\project.json, so use default config
Traceback (most recent call last):
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 41, in <module>
    update_res(ARGUMENTS, is_new_usage)
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 31, in update_res
    updater.run(locator.getAwtkRoot())
  File "D:\Devtools\awtk\scripts\update_res_app.py", line 251, in run
    theme["lcd_orientation"] = LCD_ORIENTATION
    ~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object does not support item assignment
AWTK_ROOT: D:\Devtools\awtk
AWTK_SCRIPTS_ROOT: D:\Devtools\awtk\scripts
Expecting value: line 1 column 1 (char 0)
not found or not parsered D:\Devtools\awtk-web\webroot\demouijs\project.json, so use default config
Traceback (most recent call last):
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 41, in <module>
    update_res(ARGUMENTS, is_new_usage)
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 31, in update_res
    updater.run(locator.getAwtkRoot())
  File "D:\Devtools\awtk\scripts\update_res_app.py", line 251, in run
    theme["lcd_orientation"] = LCD_ORIENTATION
    ~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object does not support item assignment
AWTK_ROOT: D:\Devtools\awtk
AWTK_SCRIPTS_ROOT: D:\Devtools\awtk\scripts
Expecting value: line 1 column 1 (char 0)
not found or not parsered D:\Devtools\awtk-web\webroot\demouijs\project.json, so use default config
Traceback (most recent call last):
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 41, in <module>
    update_res(ARGUMENTS, is_new_usage)
  File "D:\Devtools\awtk-web\webroot\demouijs\scripts\update_res.py", line 31, in update_res
    updater.run(locator.getAwtkRoot())
  File "D:\Devtools\awtk\scripts\update_res_app.py", line 251, in run
    theme["lcd_orientation"] = LCD_ORIENTATION
    ~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object does not support item assignment
```

**Comment by Tracker647** [comment]
查到了，和demoui_web.json同一路径的project.json是空的，把awtk-jerryscript根目录的project.json内容复制过去就行了。
